# Generated by Django 4.2.6 on 2023-11-20 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_remove_item_addressee_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item", old_name="sender_id", new_name="client_id",
        ),
    ]
