# Generated by Django 4.2.6 on 2023-11-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_item2address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[("line_id", models.AutoField(primary_key=True, serialize=False)),],
        ),
        migrations.CreateModel(
            name="LineAddress",
            fields=[
                ("address_id", models.BigIntegerField()),
                ("transfer_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.line"
                    ),
                ),
            ],
        ),
    ]
