# Generated by Django 4.2.6 on 2023-11-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Address_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField()),
                ("sender_id", models.BigIntegerField()),
                ("addressee_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("ship_date", models.DateTimeField(auto_now_add=True)),
                ("receive_date", models.DateTimeField(default=None)),
                ("weight", models.FloatField()),
                ("ship_address_id", models.BigIntegerField()),
                ("receive_address_id", models.BigIntegerField()),
                ("remark", models.TextField(blank=True, default="")),
                ("is_receive", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_id", models.BigIntegerField()),
                ("login_password", models.TextField()),
                ("authority_level", models.BigIntegerField()),
                ("phone", models.BigIntegerField()),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
