# Generated by Django 4.2.6 on 2023-11-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_item_is_send"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="addressee_id",),
    ]
