# Generated by Django 4.2.6 on 2023-11-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_rename_sender_id_item_client_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item2Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField()),
                ("Address_id", models.BigIntegerField()),
                ("line_id", models.IntegerField()),
                ("transfer_id", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
