# Generated by Django 4.2.6 on 2023-12-03 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_item_receive_date_item_ship_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="receive_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 3, 17, 6, 14, 810617)
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="ship_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 3, 17, 6, 14, 810617)
            ),
        ),
    ]
