# Generated by Django 4.2.6 on 2023-12-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_alter_item_receive_date_alter_item_ship_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="receive_date",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="ship_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
